create update User data by phone
lapinn-a/aqualabean-backend pull request #5
Opened 2022-04-08 19:58 UTC by kolya18

2022-04-08 20:01 UTC, kolya18 commented
TEST PUT
http://localhost:8000/api/update
{
    "phone": "+7(999)777-77-33",
    "email": "test23333@aqualabean.ru",
    "surname": "Сергеевич",
    "name": "Костя"
}

2022-04-09 05:41 UTC, lapinn-a requested changes
Не принимается, любой пользователь может изменить чужой профиль

2022-04-09 05:41 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/routes/users.routes.js
> +const tutorials = require("../controllers/tutorial.controller");
в маршрутах пользователя не требуется этот контроллер

2022-04-09 05:41 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/routes/auth.routes.js
> +    app.put("/api/update", controller.updateData);
не нужна отдельная конечная точка для обновления, можно отправлять на /api/account.

2022-04-09 05:41 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/controllers/auth.controller.js
> +};
не тот контроллер, надо в users

2022-04-09 05:41 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/controllers/auth.controller.js
> +                res.send({
ошибка с кодом 200

2022-04-09 05:41 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/controllers/auth.controller.js
> +        where: { phone: req.body.phone }
вроде уже решили искать по id? не поддерживаю решение искать по телефону

2022-04-09 05:41 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/controllers/auth.controller.js
> +                    message: `Cannot update user data with phone=${phone}. Maybe user data was not found or req.body is empty!`
когда происходит ошибка, выводится phone = undefined

2022-04-09 05:41 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/controllers/auth.controller.js
> +    User.update(req.body, {
принимает пустые поля

2022-04-09 13:14 UTC, lapinn-a reviewed
ладно сделаю пуш и приму

2022-04-09 13:14 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/controllers/users.controller.js
> +    else if (organization_id === "") return res.status(400).send({ message: "`organization_id` must not be an empty string"});
лучше в middleware проверить. будет не checkRegistration а checkUserData

2022-04-09 13:14 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/controllers/users.controller.js
> +                    res.status(200).send({
думаю фраза "ошибка с кодом 200" должна немного о другом говорить

2022-04-09 13:14 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/controllers/users.controller.js
> +                        message: `Cannot update user data with phone=${phone}. Maybe user data was not found or req.body is empty!`
я думаю фронт точно не обрадуется, если увидит "undefined" в ответе от сервера

2022-04-09 13:14 UTC, lapinn-a commented on nodejs-express-sequelize-postgresql/app/controllers/users.controller.js
> +                phone: req.body.phone
токен однозначно определяет пользователя, телефон не нужен

2022-04-09 13:16 UTC, merged